name = "minecraft quilt but not rlly"
author = "queen"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09d7977992e96ef6870151adb1e2171ec469455e6ce9a191a13c2fc33741fb72"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
