name = "minecraft quilt but not rlly"
author = "qeen"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e2382e93f4c8cf25d370df29cd74ceb990abe4025656c949aeed504718007d4"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
