name = "minecraft quilt but not rlly"
author = "queen"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e2e68a3f7d4fc7f59e8e7912d33cd8fe8db36a5422e37f722fabd9f434c6552"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
