name = "minecraft quilt but not rlly"
author = "queen"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95a0299ca1f2901fc0c53e4279982cccf7f32f42872d24d2bba281785ea7a2fa"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
