name = "minecraft quilt but not rlly"
author = "qeen"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ecc6792e42e79700915945f08c7984a8095c6ad15553013909941f4ca398e2b2"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
