name = "minecraft quilt but not rlly"
author = "queen"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5d84c998920b4f2a8a27e1227bed9c32c0ab595645135746eb7ab63bc8be645"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
